var ANDROID_KEY = {
    KEYCODE_UNKNOWN: 0,
    KEYCODE_MENU: 1,
    KEYCODE_SOFT_RIGHT: 2,
    KEYCODE_HOME: 3,
    KEYCODE_BACK: 4,
    KEYCODE_CALL: 5,
    KEYCODE_ENDCALL: 6,
    KEYCODE_0: 7,
    KEYCODE_1: 8,
    KEYCODE_2: 9,
    KEYCODE_3: 10,
    KEYCODE_4: 11,
    KEYCODE_5: 12,
    KEYCODE_6: 13,
    KEYCODE_7: 14,
    KEYCODE_8: 15,
    KEYCODE_9: 16,
    KEYCODE_STAR: 17,
    KEYCODE_POUND: 18,
    KEYCODE_DPAD_UP: 19,
    KEYCODE_DPAD_DOWN: 20,
    KEYCODE_DPAD_LEFT: 21,
    KEYCODE_DPAD_RIGHT: 22,
    KEYCODE_DPAD_CENTER: 23,
    KEYCODE_VOLUME_UP: 24,
    KEYCODE_VOLUME_DOWN: 25,
    KEYCODE_POWER: 26,
    KEYCODE_CAMERA: 27,
    KEYCODE_CLEAR: 28,
    KEYCODE_A: 29,
    KEYCODE_B: 30,
    KEYCODE_C: 31,
    KEYCODE_D: 32,
    KEYCODE_E: 33,
    KEYCODE_F: 34,
    KEYCODE_G: 35,
    KEYCODE_H: 36,
    KEYCODE_I: 37,
    KEYCODE_J: 38,
    KEYCODE_K: 39,
    KEYCODE_L: 40,
    KEYCODE_M: 41,
    KEYCODE_N: 42,
    KEYCODE_O: 43,
    KEYCODE_P: 44,
    KEYCODE_Q: 45,
    KEYCODE_R: 46,
    KEYCODE_S: 47,
    KEYCODE_T: 48,
    KEYCODE_U: 49,
    KEYCODE_V: 50,
    KEYCODE_W: 51,
    KEYCODE_X: 52,
    KEYCODE_Y: 53,
    KEYCODE_Z: 54,
    KEYCODE_COMMA: 55,
    KEYCODE_PERIOD: 56,
    KEYCODE_ALT_LEFT: 57,
    KEYCODE_ALT_RIGHT: 58,
    KEYCODE_SHIFT_LEFT: 59,
    KEYCODE_SHIFT_RIGHT: 60,
    KEYCODE_TAB: 61,
    KEYCODE_SPACE: 62,
    KEYCODE_SYM: 63,
    KEYCODE_EXPLORER: 64,
    KEYCODE_ENVELOPE: 65,
    KEYCODE_ENTER: 66,
    KEYCODE_DEL: 67,
    KEYCODE_GRAVE: 68,
    KEYCODE_MINUS: 69,
    KEYCODE_EQUALS: 70,
    KEYCODE_LEFT_BRACKET: 71,
    KEYCODE_RIGHT_BRACKET: 72,
    KEYCODE_BACKSLASH: 73,
    KEYCODE_SEMICOLON: 74,
    KEYCODE_APOSTROPHE: 75,
    KEYCODE_SLASH: 76,
    KEYCODE_AT: 77,
    KEYCODE_NUM: 78,
    KEYCODE_HEADSETHOOK: 79,
    KEYCODE_FOCUS: 80,
    KEYCODE_PLUS: 81,
    KEYCODE_MENU: 82,
    KEYCODE_NOTIFICATION: 83,
    KEYCODE_SEARCH: 84,
    TAG_LAST_KEYCODE: 85,
    KEYCODE_ESC: 111
};
var BROWSER_KEY = {
    KEY_A: 65,
    KEY_B: 66,
    KEY_C: 67,
    KEY_D: 68,
    KEY_E: 69,
    KEY_F: 70,
    KEY_G: 71,
    KEY_H: 72,
    KEY_I: 73,
    KEY_J: 74,
    KEY_K: 75,
    KEY_L: 76,
    KEY_M: 77,
    KEY_N: 78,
    KEY_O: 79,
    KEY_P: 80,
    KEY_Q: 81,
    KEY_R: 82,
    KEY_S: 83,
    KEY_T: 84,
    KEY_U: 85,
    KEY_V: 86,
    KEY_W: 87,
    KEY_X: 88,
    KEY_Y: 89,
    KEY_Z: 90,
    KEY_0: 48,
    KEY_1: 49,
    KEY_2: 50,
    KEY_3: 51,
    KEY_4: 52,
    KEY_5: 53,
    KEY_6: 54,
    KEY_7: 55,
    KEY_8: 56,
    KEY_9: 57,
    KEY_STAR: 56,
    KEY_NUM_STAR: 106,
    KEY_COMMA: 188,
    KEY_NUM_0: 96,
    KEY_NUM_1: 97,
    KEY_NUM_2: 98,
    KEY_NUM_3: 99,
    KEY_NUM_4: 100,
    KEY_NUM_5: 101,
    KEY_NUM_6: 102,
    KEY_NUM_7: 103,
    KEY_NUM_8: 104,
    KEY_NUM_9: 105,
    KEY_SPACE: 32,
    KEY_ENTER: 13,
    KEY_DEL: 46,
    KEY_UP: 38,
    KEY_DOWN: 40,
    KEY_LEFT: 37,
    KEY_RIGHT: 39,
    KEY_ESC: 27,
    KEY_HOME: 36,
    KEY_BACKSPACE:8,
    KEY_TAB:9
};
var CONSOLE_KEY = {
    KEY_A: "a",
    KEY_B: "b",
    KEY_C: "c",
    KEY_D: "d",
    KEY_E: "e",
    KEY_F: "f",
    KEY_G: "g",
    KEY_H: "h",
    KEY_I: "i",
    KEY_J: "j",
    KEY_K: "k",
    KEY_L: "l",
    KEY_M: "m",
    KEY_N: "n",
    KEY_O: "o",
    KEY_P: "p",
    KEY_Q: "q",
    KEY_R: "r",
    KEY_S: "s",
    KEY_T: "t",
    KEY_U: "u",
    KEY_V: "v",
    KEY_W: "w",
    KEY_X: "x",
    KEY_Y: "y",
    KEY_Z: "z",
    KEY_0: "0",
    KEY_1: "1",
    KEY_2: "2",
    KEY_3: "3",
    KEY_4: "4",
    KEY_5: "5",
    KEY_6: "6",
    KEY_7: "7",
    KEY_8: "8",
    KEY_9: "9",
    KEY_STAR: "*",
    KEY_COMMA: ",",
    KEY_SPACE: "space",
    KEY_ENTER: "enter",
    KEY_DEL: "delete",
    KEY_UP: "up",
    KEY_DOWN: "down",
    KEY_LEFT: "left",
    KEY_RIGHT: "right",
    KEY_ESC: "escape",
    KEY_HOME: "home",
    KEY_BACKSPACE: "backspace",
    KEY_TAB: "tab"
};
var mappings = {};
if (require) {
//        mappings[CONSOLE_KEY.KEY_UNKNOWN] = ANDROID_KEY.KEYCODE_UNKNOWN;
//        mappings[CONSOLE_KEY.KEY_MENU] = ANDROID_KEY.KEYCODE_MENU;
//        mappings[CONSOLE_KEY.KEY_SOFT_RIGHT] = ANDROID_KEY.KEYCODE_SOFT_RIGHT;
    mappings[CONSOLE_KEY.KEY_HOME] = ANDROID_KEY.KEYCODE_HOME;
    mappings[CONSOLE_KEY.KEY_ESC] = ANDROID_KEY.KEYCODE_ESC;
    mappings[CONSOLE_KEY.KEY_BACKSPACE] = ANDROID_KEY.KEYCODE_BACK;
    mappings[CONSOLE_KEY.KEY_TAB] = ANDROID_KEY.KEYCODE_TAB;
//        mappings[CONSOLE_KEY.KEY_CALL] = ANDROID_KEY.KEYCODE_CALL;
//        mappings[CONSOLE_KEY.KEY_ENDCALL] = ANDROID_KEY.KEYCODE_ENDCALL;
    mappings[CONSOLE_KEY.KEY_0] = ANDROID_KEY.KEYCODE_0;
    mappings[CONSOLE_KEY.KEY_1] = ANDROID_KEY.KEYCODE_1;
    mappings[CONSOLE_KEY.KEY_2] = ANDROID_KEY.KEYCODE_2;
    mappings[CONSOLE_KEY.KEY_3] = ANDROID_KEY.KEYCODE_3;
    mappings[CONSOLE_KEY.KEY_4] = ANDROID_KEY.KEYCODE_4;
    mappings[CONSOLE_KEY.KEY_5] = ANDROID_KEY.KEYCODE_5;
    mappings[CONSOLE_KEY.KEY_6] = ANDROID_KEY.KEYCODE_6;
    mappings[CONSOLE_KEY.KEY_7] = ANDROID_KEY.KEYCODE_7;
    mappings[CONSOLE_KEY.KEY_8] = ANDROID_KEY.KEYCODE_8;
    mappings[CONSOLE_KEY.KEY_9] = ANDROID_KEY.KEYCODE_9;
    mappings[CONSOLE_KEY.KEY_NUM_0] = ANDROID_KEY.KEYCODE_0;
    mappings[CONSOLE_KEY.KEY_NUM_1] = ANDROID_KEY.KEYCODE_1;
    mappings[CONSOLE_KEY.KEY_NUM_2] = ANDROID_KEY.KEYCODE_2;
    mappings[CONSOLE_KEY.KEY_NUM_3] = ANDROID_KEY.KEYCODE_3;
    mappings[CONSOLE_KEY.KEY_NUM_4] = ANDROID_KEY.KEYCODE_4;
    mappings[CONSOLE_KEY.KEY_NUM_5] = ANDROID_KEY.KEYCODE_5;
    mappings[CONSOLE_KEY.KEY_NUM_6] = ANDROID_KEY.KEYCODE_6;
    mappings[CONSOLE_KEY.KEY_NUM_7] = ANDROID_KEY.KEYCODE_7;
    mappings[CONSOLE_KEY.KEY_NUM_8] = ANDROID_KEY.KEYCODE_8;
    mappings[CONSOLE_KEY.KEY_NUM_9] = ANDROID_KEY.KEYCODE_9;
//        mappings[CONSOLE_KEY.KEY_STAR] = ANDROID_KEY.KEYCODE_STAR;
//        mappings[CONSOLE_KEY.KEY_POUND] = ANDROID_KEY.KEYCODE_POUND;
    mappings[CONSOLE_KEY.KEY_UP] = ANDROID_KEY.KEYCODE_DPAD_UP;
    mappings[CONSOLE_KEY.KEY_DOWN] = ANDROID_KEY.KEYCODE_DPAD_DOWN;
    mappings[CONSOLE_KEY.KEY_LEFT] = ANDROID_KEY.KEYCODE_DPAD_LEFT;
    mappings[CONSOLE_KEY.KEY_RIGHT] = ANDROID_KEY.KEYCODE_DPAD_RIGHT;
//        mappings[CONSOLE_KEY.KEY_CENTER] = ANDROID_KEY.KEYCODE_DPAD_CENTER;
//        mappings[CONSOLE_KEY.KEY_VOLUME_UP] = ANDROID_KEY.KEYCODE_VOLUME_UP;
//        mappings[CONSOLE_KEY.KEY_VOLUME_DOWN] = ANDROID_KEY.KEYCODE_VOLUME_DOWN;
//        mappings[CONSOLE_KEY.KEY_POWER] = ANDROID_KEY.KEYCODE_POWER;
//        mappings[CONSOLE_KEY.KEY_CAMERA] = ANDROID_KEY.KEYCODE_CAMERA;
//        mappings[CONSOLE_KEY.KEY_CLEAR] = ANDROID_KEY.KEYCODE_CLEAR;
    mappings[CONSOLE_KEY.KEY_A] = ANDROID_KEY.KEYCODE_A;
    mappings[CONSOLE_KEY.KEY_B] = ANDROID_KEY.KEYCODE_B;
    mappings[CONSOLE_KEY.KEY_C] = ANDROID_KEY.KEYCODE_C;
    mappings[CONSOLE_KEY.KEY_D] = ANDROID_KEY.KEYCODE_D;
    mappings[CONSOLE_KEY.KEY_E] = ANDROID_KEY.KEYCODE_E;
    mappings[CONSOLE_KEY.KEY_F] = ANDROID_KEY.KEYCODE_F;
    mappings[CONSOLE_KEY.KEY_G] = ANDROID_KEY.KEYCODE_G;
    mappings[CONSOLE_KEY.KEY_H] = ANDROID_KEY.KEYCODE_H;
    mappings[CONSOLE_KEY.KEY_I] = ANDROID_KEY.KEYCODE_I;
    mappings[CONSOLE_KEY.KEY_J] = ANDROID_KEY.KEYCODE_J;
    mappings[CONSOLE_KEY.KEY_K] = ANDROID_KEY.KEYCODE_K;
    mappings[CONSOLE_KEY.KEY_L] = ANDROID_KEY.KEYCODE_L;
    mappings[CONSOLE_KEY.KEY_M] = ANDROID_KEY.KEYCODE_M;
    mappings[CONSOLE_KEY.KEY_N] = ANDROID_KEY.KEYCODE_N;
    mappings[CONSOLE_KEY.KEY_O] = ANDROID_KEY.KEYCODE_O;
    mappings[CONSOLE_KEY.KEY_P] = ANDROID_KEY.KEYCODE_P;
    mappings[CONSOLE_KEY.KEY_Q] = ANDROID_KEY.KEYCODE_Q;
    mappings[CONSOLE_KEY.KEY_R] = ANDROID_KEY.KEYCODE_R;
    mappings[CONSOLE_KEY.KEY_S] = ANDROID_KEY.KEYCODE_S;
    mappings[CONSOLE_KEY.KEY_T] = ANDROID_KEY.KEYCODE_T;
    mappings[CONSOLE_KEY.KEY_U] = ANDROID_KEY.KEYCODE_U;
    mappings[CONSOLE_KEY.KEY_V] = ANDROID_KEY.KEYCODE_V;
    mappings[CONSOLE_KEY.KEY_W] = ANDROID_KEY.KEYCODE_W;
    mappings[CONSOLE_KEY.KEY_X] = ANDROID_KEY.KEYCODE_X;
    mappings[CONSOLE_KEY.KEY_Y] = ANDROID_KEY.KEYCODE_Y;
    mappings[CONSOLE_KEY.KEY_Z] = ANDROID_KEY.KEYCODE_Z;
//        mappings[CONSOLE_KEY.KEY_COMMA] = ANDROID_KEY.KEYCODE_COMMA;
//        mappings[CONSOLE_KEY.KEY_PERIOD] = ANDROID_KEY.KEYCODE_PERIOD;
//        mappings[CONSOLE_KEY.KEY_ALT_LEFT] = ANDROID_KEY.KEYCODE_ALT_LEFT;
//        mappings[CONSOLE_KEY.KEY_ALT_RIGHT] = ANDROID_KEY.KEYCODE_ALT_RIGHT;
//        mappings[CONSOLE_KEY.KEY_SHIFT_LEFT] = ANDROID_KEY.KEYCODE_SHIFT_LEFT;
//        mappings[CONSOLE_KEY.KEY_SHIFT_RIGHT] = ANDROID_KEY.KEYCODE_SHIFT_RIGHT;
    mappings[CONSOLE_KEY.KEY_SPACE] = ANDROID_KEY.KEYCODE_SPACE;
//        mappings[CONSOLE_KEY.KEY_SYM] = ANDROID_KEY.KEYCODE_SYM;
//        mappings[CONSOLE_KEY.KEY_EXPLORER] = ANDROID_KEY.KEYCODE_EXPLORER;
//        mappings[CONSOLE_KEY.KEY_ENVELOPE] = ANDROID_KEY.KEYCODE_ENVELOPE;
    mappings[CONSOLE_KEY.KEY_ENTER] = ANDROID_KEY.KEYCODE_ENTER;
    mappings[CONSOLE_KEY.KEY_DEL] = ANDROID_KEY.KEYCODE_DEL;
//        mappings[CONSOLE_KEY.KEY_GRAVE] = ANDROID_KEY.KEYCODE_GRAVE;
//        mappings[CONSOLE_KEY.KEY_MINUS] = ANDROID_KEY.KEYCODE_MINUS;
//        mappings[CONSOLE_KEY.KEY_EQUALS] = ANDROID_KEY.KEYCODE_EQUALS;
//        mappings[CONSOLE_KEY.KEY_LEFT_BRACKET] = ANDROID_KEY.KEYCODE_LEFT_BRACKET;
//        mappings[CONSOLE_KEY.KEY_RIGHT_BRACKET] = ANDROID_KEY.KEYCODE_RIGHT_BRACKET;
//        mappings[CONSOLE_KEY.KEY_BACKSLASH] = ANDROID_KEY.KEYCODE_BACKSLASH;
//        mappings[CONSOLE_KEY.KEY_SEMICOLON] = ANDROID_KEY.KEYCODE_SEMICOLON;
//        mappings[CONSOLE_KEY.KEY_APOSTROPHE] = ANDROID_KEY.KEYCODE_APOSTROPHE;
//        mappings[CONSOLE_KEY.KEY_SLASH] = ANDROID_KEY.KEYCODE_SLASH;
//        mappings[CONSOLE_KEY.KEY_AT] = ANDROID_KEY.KEYCODE_AT;
//        mappings[CONSOLE_KEY.KEY_NUM] = ANDROID_KEY.KEYCODE_NUM;
//        mappings[CONSOLE_KEY.KEY_HEADSETHOOK] = ANDROID_KEY.KEYCODE_HEADSETHOOK;
//        mappings[CONSOLE_KEY.KEY_FOCUS] = ANDROID_KEY.KEYCODE_FOCUS;
//        mappings[CONSOLE_KEY.KEY_PLUS] = ANDROID_KEY.KEYCODE_PLUS;
//        mappings[CONSOLE_KEY.KEY_MENU] = ANDROID_KEY.KEYCODE_MENU;
//        mappings[CONSOLE_KEY.KEY_NOTIFICATION] = ANDROID_KEY.KEYCODE_NOTIFICATION;
//        mappings[CONSOLE_KEY.KEY_SEARCH] = ANDROID_KEY.KEYCODE_SEARCH;
//        mappings[CONSOLE_KEY.TAG_LAST_KEY] = ANDROID_KEY.TAG_LAST_KEYCODE;
}else{
//        mappings[BROWSER_KEY.KEY_UNKNOWN] = ANDROID_KEY.KEYCODE_UNKNOWN;
//        mappings[BROWSER_KEY.KEY_MENU] = ANDROID_KEY.KEYCODE_MENU;
//        mappings[BROWSER_KEY.KEY_SOFT_RIGHT] = ANDROID_KEY.KEYCODE_SOFT_RIGHT;
    mappings[BROWSER_KEY.KEY_HOME] = ANDROID_KEY.KEYCODE_HOME;
    mappings[BROWSER_KEY.KEY_ESC] = ANDROID_KEY.KEYCODE_ESC;
    mappings[BROWSER_KEY.KEY_BACKSPACE] = ANDROID_KEY.KEYCODE_BACK;
    mappings[BROWSER_KEY.KEY_TAB] = ANDROID_KEY.KEYCODE_TAB;
//        mappings[BROWSER_KEY.KEY_CALL] = ANDROID_KEY.KEYCODE_CALL;
//        mappings[BROWSER_KEY.KEY_ENDCALL] = ANDROID_KEY.KEYCODE_ENDCALL;
    mappings[BROWSER_KEY.KEY_0] = ANDROID_KEY.KEYCODE_0;
    mappings[BROWSER_KEY.KEY_1] = ANDROID_KEY.KEYCODE_1;
    mappings[BROWSER_KEY.KEY_2] = ANDROID_KEY.KEYCODE_2;
    mappings[BROWSER_KEY.KEY_3] = ANDROID_KEY.KEYCODE_3;
    mappings[BROWSER_KEY.KEY_4] = ANDROID_KEY.KEYCODE_4;
    mappings[BROWSER_KEY.KEY_5] = ANDROID_KEY.KEYCODE_5;
    mappings[BROWSER_KEY.KEY_6] = ANDROID_KEY.KEYCODE_6;
    mappings[BROWSER_KEY.KEY_7] = ANDROID_KEY.KEYCODE_7;
    mappings[BROWSER_KEY.KEY_8] = ANDROID_KEY.KEYCODE_8;
    mappings[BROWSER_KEY.KEY_9] = ANDROID_KEY.KEYCODE_9;
    mappings[BROWSER_KEY.KEY_NUM_0] = ANDROID_KEY.KEYCODE_0;
    mappings[BROWSER_KEY.KEY_NUM_1] = ANDROID_KEY.KEYCODE_1;
    mappings[BROWSER_KEY.KEY_NUM_2] = ANDROID_KEY.KEYCODE_2;
    mappings[BROWSER_KEY.KEY_NUM_3] = ANDROID_KEY.KEYCODE_3;
    mappings[BROWSER_KEY.KEY_NUM_4] = ANDROID_KEY.KEYCODE_4;
    mappings[BROWSER_KEY.KEY_NUM_5] = ANDROID_KEY.KEYCODE_5;
    mappings[BROWSER_KEY.KEY_NUM_6] = ANDROID_KEY.KEYCODE_6;
    mappings[BROWSER_KEY.KEY_NUM_7] = ANDROID_KEY.KEYCODE_7;
    mappings[BROWSER_KEY.KEY_NUM_8] = ANDROID_KEY.KEYCODE_8;
    mappings[BROWSER_KEY.KEY_NUM_9] = ANDROID_KEY.KEYCODE_9;
//        mappings[BROWSER_KEY.KEY_STAR] = ANDROID_KEY.KEYCODE_STAR;
//        mappings[BROWSER_KEY.KEY_POUND] = ANDROID_KEY.KEYCODE_POUND;
    mappings[BROWSER_KEY.KEY_UP] = ANDROID_KEY.KEYCODE_DPAD_UP;
    mappings[BROWSER_KEY.KEY_DOWN] = ANDROID_KEY.KEYCODE_DPAD_DOWN;
    mappings[BROWSER_KEY.KEY_LEFT] = ANDROID_KEY.KEYCODE_DPAD_LEFT;
    mappings[BROWSER_KEY.KEY_RIGHT] = ANDROID_KEY.KEYCODE_DPAD_RIGHT;
//        mappings[BROWSER_KEY.KEY_CENTER] = ANDROID_KEY.KEYCODE_DPAD_CENTER;
//        mappings[BROWSER_KEY.KEY_VOLUME_UP] = ANDROID_KEY.KEYCODE_VOLUME_UP;
//        mappings[BROWSER_KEY.KEY_VOLUME_DOWN] = ANDROID_KEY.KEYCODE_VOLUME_DOWN;
//        mappings[BROWSER_KEY.KEY_POWER] = ANDROID_KEY.KEYCODE_POWER;
//        mappings[BROWSER_KEY.KEY_CAMERA] = ANDROID_KEY.KEYCODE_CAMERA;
//        mappings[BROWSER_KEY.KEY_CLEAR] = ANDROID_KEY.KEYCODE_CLEAR;
    mappings[BROWSER_KEY.KEY_A] = ANDROID_KEY.KEYCODE_A;
    mappings[BROWSER_KEY.KEY_B] = ANDROID_KEY.KEYCODE_B;
    mappings[BROWSER_KEY.KEY_C] = ANDROID_KEY.KEYCODE_C;
    mappings[BROWSER_KEY.KEY_D] = ANDROID_KEY.KEYCODE_D;
    mappings[BROWSER_KEY.KEY_E] = ANDROID_KEY.KEYCODE_E;
    mappings[BROWSER_KEY.KEY_F] = ANDROID_KEY.KEYCODE_F;
    mappings[BROWSER_KEY.KEY_G] = ANDROID_KEY.KEYCODE_G;
    mappings[BROWSER_KEY.KEY_H] = ANDROID_KEY.KEYCODE_H;
    mappings[BROWSER_KEY.KEY_I] = ANDROID_KEY.KEYCODE_I;
    mappings[BROWSER_KEY.KEY_J] = ANDROID_KEY.KEYCODE_J;
    mappings[BROWSER_KEY.KEY_K] = ANDROID_KEY.KEYCODE_K;
    mappings[BROWSER_KEY.KEY_L] = ANDROID_KEY.KEYCODE_L;
    mappings[BROWSER_KEY.KEY_M] = ANDROID_KEY.KEYCODE_M;
    mappings[BROWSER_KEY.KEY_N] = ANDROID_KEY.KEYCODE_N;
    mappings[BROWSER_KEY.KEY_O] = ANDROID_KEY.KEYCODE_O;
    mappings[BROWSER_KEY.KEY_P] = ANDROID_KEY.KEYCODE_P;
    mappings[BROWSER_KEY.KEY_Q] = ANDROID_KEY.KEYCODE_Q;
    mappings[BROWSER_KEY.KEY_R] = ANDROID_KEY.KEYCODE_R;
    mappings[BROWSER_KEY.KEY_S] = ANDROID_KEY.KEYCODE_S;
    mappings[BROWSER_KEY.KEY_T] = ANDROID_KEY.KEYCODE_T;
    mappings[BROWSER_KEY.KEY_U] = ANDROID_KEY.KEYCODE_U;
    mappings[BROWSER_KEY.KEY_V] = ANDROID_KEY.KEYCODE_V;
    mappings[BROWSER_KEY.KEY_W] = ANDROID_KEY.KEYCODE_W;
    mappings[BROWSER_KEY.KEY_X] = ANDROID_KEY.KEYCODE_X;
    mappings[BROWSER_KEY.KEY_Y] = ANDROID_KEY.KEYCODE_Y;
    mappings[BROWSER_KEY.KEY_Z] = ANDROID_KEY.KEYCODE_Z;
//        mappings[BROWSER_KEY.KEY_COMMA] = ANDROID_KEY.KEYCODE_COMMA;
//        mappings[BROWSER_KEY.KEY_PERIOD] = ANDROID_KEY.KEYCODE_PERIOD;
//        mappings[BROWSER_KEY.KEY_ALT_LEFT] = ANDROID_KEY.KEYCODE_ALT_LEFT;
//        mappings[BROWSER_KEY.KEY_ALT_RIGHT] = ANDROID_KEY.KEYCODE_ALT_RIGHT;
//        mappings[BROWSER_KEY.KEY_SHIFT_LEFT] = ANDROID_KEY.KEYCODE_SHIFT_LEFT;
//        mappings[BROWSER_KEY.KEY_SHIFT_RIGHT] = ANDROID_KEY.KEYCODE_SHIFT_RIGHT;
    mappings[BROWSER_KEY.KEY_SPACE] = ANDROID_KEY.KEYCODE_SPACE;
//        mappings[BROWSER_KEY.KEY_SYM] = ANDROID_KEY.KEYCODE_SYM;
//        mappings[BROWSER_KEY.KEY_EXPLORER] = ANDROID_KEY.KEYCODE_EXPLORER;
//        mappings[BROWSER_KEY.KEY_ENVELOPE] = ANDROID_KEY.KEYCODE_ENVELOPE;
    mappings[BROWSER_KEY.KEY_ENTER] = ANDROID_KEY.KEYCODE_ENTER;
    mappings[BROWSER_KEY.KEY_DEL] = ANDROID_KEY.KEYCODE_DEL;
//        mappings[BROWSER_KEY.KEY_GRAVE] = ANDROID_KEY.KEYCODE_GRAVE;
//        mappings[BROWSER_KEY.KEY_MINUS] = ANDROID_KEY.KEYCODE_MINUS;
//        mappings[BROWSER_KEY.KEY_EQUALS] = ANDROID_KEY.KEYCODE_EQUALS;
//        mappings[BROWSER_KEY.KEY_LEFT_BRACKET] = ANDROID_KEY.KEYCODE_LEFT_BRACKET;
//        mappings[BROWSER_KEY.KEY_RIGHT_BRACKET] = ANDROID_KEY.KEYCODE_RIGHT_BRACKET;
//        mappings[BROWSER_KEY.KEY_BACKSLASH] = ANDROID_KEY.KEYCODE_BACKSLASH;
//        mappings[BROWSER_KEY.KEY_SEMICOLON] = ANDROID_KEY.KEYCODE_SEMICOLON;
//        mappings[BROWSER_KEY.KEY_APOSTROPHE] = ANDROID_KEY.KEYCODE_APOSTROPHE;
//        mappings[BROWSER_KEY.KEY_SLASH] = ANDROID_KEY.KEYCODE_SLASH;
//        mappings[BROWSER_KEY.KEY_AT] = ANDROID_KEY.KEYCODE_AT;
//        mappings[BROWSER_KEY.KEY_NUM] = ANDROID_KEY.KEYCODE_NUM;
//        mappings[BROWSER_KEY.KEY_HEADSETHOOK] = ANDROID_KEY.KEYCODE_HEADSETHOOK;
//        mappings[BROWSER_KEY.KEY_FOCUS] = ANDROID_KEY.KEYCODE_FOCUS;
//        mappings[BROWSER_KEY.KEY_PLUS] = ANDROID_KEY.KEYCODE_PLUS;
//        mappings[BROWSER_KEY.KEY_MENU] = ANDROID_KEY.KEYCODE_MENU;
//        mappings[BROWSER_KEY.KEY_NOTIFICATION] = ANDROID_KEY.KEYCODE_NOTIFICATION;
//        mappings[BROWSER_KEY.KEY_SEARCH] = ANDROID_KEY.KEYCODE_SEARCH;
//        mappings[BROWSER_KEY.TAG_LAST_KEY] = ANDROID_KEY.TAG_LAST_KEYCODE;
}
function sendAndroidKeycode(keycode) {
    if (keycode !== undefined){
        var cmd = "adb shell input keyevent " + keycode;
        console.log(cmd);
        execSync(cmd);
    }

}

var execSync = require("exec-sync");
var keypress = require("keypress");
keypress(process.stdin);

process.stdin.on("keypress", function (chunk, key) {
    if (key && key.ctrl && key.name == 'c') process.exit();
    if (key !== undefined)
        chunk = key.name;
    if (mappings[chunk])
        sendAndroidKeycode(mappings[chunk]);
    else{
        process.stdout.write("chunk: " + chunk + "\n");
        process.stdout.write("key: " + JSON.stringify(key, null, " ") + "\n");
    }

});

process.stdin.setRawMode(true);
process.stdin.resume();